SELECT info.PRESENT_ADDRESS, info.CARDNO, info.EMPNAME, info.FATHER_NAME, info.SECTIONNM 
FROM TB_PERSONAL_INFO info
WHERE info.PRESENT_ADDRESS LIKE '%Gazipur%'
AND   info.ACTIVE = 0
ORDER BY info.PRESENT_ADDRESS ASC